version: "3.9"

networks:
  async-network:

volumes:
  rabbitdb:

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    hostname: rabbitmq
    networks:
      - async-network
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitdb:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
  producer:
    build: ./producer
    container_name: producer
    hostname: producer
    networks:
      - async-network
    ports:
      - 3002:3000
    environment:
      - RABBITMQ_HOST=amqp://user:password@rabbitmq:5672
      - QUEUE=hello
  consumer:
    build: ./consumer
    container_name: consumer
    hostname: consumer
    networks:
      - async-network
    ports:
      - 3001:3000
    environment:
      - RABBITMQ_HOST=amqp://user:password@rabbitmq:5672
      - QUEUE=hello
    depends_on:
      - rabbitmq
